import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface-dim": "#10131a",
          "on-primary-container": "#00285d",
          "on-surface": "#e1e2ec",
          "primary-fixed": "#d8e2ff",
          "inverse-primary": "#005ac2",
          "on-secondary-fixed": "#341100",
          "surface-container-highest": "#32353c",
          "on-secondary-container": "#4a1c00",
          "on-primary": "#002e6a",
          "secondary-fixed-dim": "#ffb690",
          "on-tertiary-container": "#461f00",
          "on-primary-fixed": "#001a42",
          "outline-variant": "#424754",
          "on-error": "#690005",
          "inverse-surface": "#e1e2ec",
          "surface": "#10131a",
          "tertiary": "#ffb786",
          "on-surface-variant": "#c2c6d6",
          "on-tertiary-fixed": "#311400",
          "inverse-on-surface": "#2e3038",
          "surface-container": "#1d2027",
          "primary-fixed-dim": "#adc6ff",
          "tertiary-container": "#df7412",
          "on-secondary-fixed-variant": "#783200",
          "secondary-container": "#ec6a06",
          "primary-container": "#4d8eff",
          "error": "#ffb4ab",
          "background": "#10131a",
          "surface-variant": "#32353c",
          "error-container": "#93000a",
          "primary": "#adc6ff",
          "outline": "#8c909f",
          "on-primary-fixed-variant": "#004395",
          "surface-bright": "#363941",
          "tertiary-fixed-dim": "#ffb786",
          "surface-tint": "#adc6ff",
          "secondary": "#ffb690",
          "surface-container-high": "#272a31",
          "on-tertiary": "#502400",
          "on-tertiary-fixed-variant": "#723600",
          "surface-container-low": "#191b23",
          "surface-container-lowest": "#0b0e15",
          "on-background": "#e1e2ec",
          "on-secondary": "#552100",
          "on-error-container": "#ffdad6",
          "tertiary-fixed": "#ffdcc6",
          "secondary-fixed": "#ffdbca"
      },
      "fontFamily": {
          "body-md": ["Inter", "sans-serif"],
          "label-caps": ["Inter", "sans-serif"],
          "technical-sm": ["JetBrains Mono", "monospace"],
          "display-lg": ["Inter", "sans-serif"],
          "headline-md": ["Inter", "sans-serif"],
          "display-lg-mobile": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
          "technical-sm": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
          "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
export default config;
